# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  coreSolution: 'src\FreshMvvmCore.sln'
  coreCSProj: 'src\FreshMvvm\*.csproj'
  testCSProj: 'src\FreshMvvm.Tests\*.csproj'

pool:
    vmImage: vs2017-win2016

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.9.1'

- script: dotnet restore

- task: MSBuild@1
  displayName: Build FreshMvvm Test Project
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true
    msbuildArguments: '/t:restore'

- task: VSBuild@1
  displayName: Build FreshMvvm Core Project
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true



