# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  coreSolution: 'src\FreshMvvmCore.sln'
  coreCSProj: 'src\FreshMvvm\*.csproj'
  testDll: 'src\FreshMvvm.Tests\bin\Release\netcoreapp2.1\FreshMvvm.Tests.dll'

pool:
    vmImage: vs2017-win2016

steps:
- task: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Restore'

- task: VSBuild@1
  displayName: Build FreshMvvm Core Solution
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true
    msbuildArgs: '/t:Pack'

- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    testAssemblyVer2: '$(testDll)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/22ade35f-89d3-4515-811a-b17e54ebbb0b'






