# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  coreSolution: 'src\FreshMvvmCore.sln'
  coreCSProj: 'src\FreshMvvm\*.csproj'
  testCSProj: 'src\FreshMvvm.Tests\*.csproj'

pool:
    vmImage: vs2017-win2016

steps:

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  displayName: Build FreshMvvm Core Project
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'

- task: MSBuild@1
  displayName: Build FreshMvvm Test Project
  inputs:
    solution: '$(testCSProj)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true

